Repository wiremock/wiremock.org, pull requests merged in 2023-04, with the labels that each got.

#30 Modify all website Slack links to use the redirect
  _config.yml
  _data/navigation.yml
  index.html
  support/index.md
Labels: bug

#36 Add @oleg-nenashev to CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#40 Refresh the navigation bar
  _data/navigation.yml
Labels: enhancement

#45 Enable compression on the deployed website
  .github/workflows/deploy.yaml
Labels: chore

#47 Enable Continuous Integration for the website
  .github/workflows/ci.yml
Labels: chore

#41 Add filename-support documentation
  _docs/configuration.md
  _docs/running-standalone.md
  assets/js/wiremock-admin-api.json
Labels: documentation, enhancement

#48 Explicitly reference bundle exec in the contributor guide
  CONTRIBUTING.md
Labels: chore

#50 Create dependabot.yml for submodule updates
  .github/dependabot.yml
Labels: chore

#52 Better navigation for preview documents
  CONTRIBUTING.md
  _config-3.x.yml
  _config.yml
  _data/baselines.yml
  _data/navigation.yml
  _includes/masthead.html
  _layouts/docs.html
Labels: documentation

#55 Use HTTPs Slack redirect link
  CONTRIBUTING.md
  _config.yml
  _data/navigation.yml
  index.html
  support/index.md
Labels: chore

#61 Add social sharing metadata
  _config.yml
Labels: enhancement
