Repository wiremock/wiremock.org, pull requests merged in 2023-09, with the labels that each got.

#165 Add support for rendering code tabs
  _docs/request-matching.md
  _docs/stubbing.md
  _layouts/docs.html
  _plugins/jekyll-code-tabs.rb
  lib/jekyll-code-tabs.rb
  lib/jekyll-code-tabs/version.rb
Labels: enhancement

#168 Update locations of the Python WireMock library
  _docs/solutions/python.md
Labels: documentation

#163 chore: remove preview setup
  .scripts/build-preview.sh
  .scripts/preview-publish.sh
  _config_preview_public.yml
Labels: chore, needs_tom

#175 fix: make css grid container responsive in docs page
  _docs/index.html
Labels: enhancement

#176 Hacktoberfest page + announcement on the landing + Custom opengraph support
  _includes/seo.html
  _sass/_homepage.scss
  events/hacktoberfest.md
  images/events/hacktoberfest/wiremock_hacktoberfest_header.png
  images/events/hacktoberfest/wiremock_hacktoberfest_opengraph.png
  images/events/hacktoberfest/wiremock_tshirts.png
  index.html
Labels: enhancement

#179 Add IntelliJ run configurations for building and running the website
  .run/Build website.run.xml
  .run/Bundle install.run.xml
  .run/Run website.run.xml
Labels: chore

#185 Change notice to announce Hacktoberfest instead
  assets/js/notifications.js
Labels: community

#184 Document code tabs in the contributor guide
  CONTRIBUTING.md
Labels: community

#188 Add gRPC and GraphQL to the solution pages
  _data/doc-categories.yml
  _docs/grpc.md
  _docs/index.html
  _docs/solutions/graphql.md
  images/logos/technology/graphql.svg
  images/logos/technology/grpc.png
  images/logos/technology/http.svg
  images/logos/technology/https.svg
  images/logos/technology/webhooks.svg
  images/solutions/graphql/wiremock_graphql_opengraph.png
  images/solutions/grpc/header.png
  images/solutions/grpc/intro_schema.png
  images/solutions/grpc/wiremock-grpc-opengraph.png
  images/wiremock-cloud/wiremock_cloud_favicon.svg
  images/wiremock-cloud/wiremock_cloud_logo.svg
Labels: documentation, enhancement

#187 Add WireMock Spring Boot to the Solutions page
  _docs/solutions/spring-boot.md
Labels: documentation

#189 Add a solution page for and Testcontainers C/C++
  _docs/index.html
  _docs/solutions/c_cpp.md
  _docs/solutions/testcontainers.md
  images/logos/technology/c.png
  images/logos/technology/cpp.png
  images/solutions/testcontainers/testcontainers_c_logo_square.png
  images/solutions/testcontainers/testcontainers_c_logo_wide.png
  images/solutions/testcontainers/testcontainers_c_opengraph.png
Labels: documentation

#190 Rust solutions page
  _docs/solutions/rust.md
Labels: documentation
