Repository wiremock/wiremock.org, pull requests merged in 2023-10, with the labels that each got.

#203 Add Redirects for testcontainers root links
  _docs/solutions/testcontainers.md
Labels: enhancement

#204 Add issue filters to the hacktoberfest page
  events/hacktoberfest.md
Labels: enhancement

#202 Fix broken link
  events/hacktoberfest.md
Labels: bug

#209 Hacktoberfest: Add a link to the recording and featured projects
  events/hacktoberfest.md
Labels: community

#178 Add Frequently Asked Questions page
  _data/doc-categories.yml
  _docs/faq.md
Labels: documentation

#212 doc: remove non existstant havingExactly reference
  _docs/request-matching.md
Labels: bug

#215 Hacktoberfest: Expand featured projects, add more filters and searches
  events/hacktoberfest.md
Labels: documentation

#216 documentation for wiremock options as env variable in docker
  _docs/standalone/docker.md
Labels: documentation

#220 ci: automate wiremock version update
  .github/updatecli/updatecli.d/wiremock.yaml
  .github/workflows/updatecli.yaml
Labels: chore, hacktoberfest-accepted

#221 Update docker.md
  _docs/standalone/docker.md
Labels: documentation, hacktoberfest-accepted

#219 outdated documentation for ResponseTemplateTransformer
  _docs/response-templating.md
Labels: documentation

#222 Add NPM to distributions list
  _docs/index.html
  images/logos/technology/npm.svg
Labels: documentation, hacktoberfest-accepted
