Repository wiremock/wiremock.org, pull requests merged in 2023-05, with the labels that each got.

#67 Fix the positioning of the article links in External Resources
  external-resources/index.html
Labels: bug

#65 Existing Documentation Restructuring
  _data/doc-categories.yml
  _docs/advanced/deploy-to-servlet-container.md
  _docs/advanced/java7.md
  _docs/download-and-installation.md
  _docs/getting-started.md
  _docs/https.md
  _docs/java-usage.md
  _docs/junit-extensions.md
  _docs/junit-jupiter.md
  _docs/overview.md
  _docs/quickstart/java-junit.md
  _docs/standalone/admin-api-reference.md
  _docs/standalone/administration.md
  _docs/standalone/java-jar.md
Labels: documentation, enhancement

#74 Document Java solution
  _docs/docker.md
  _docs/index.html
  _docs/java-usage.md
  _docs/solutions/android.md
  _docs/solutions/groovy.md
  _docs/solutions/jvm.md
  _docs/solutions/spring-boot.md
  _layouts/solution.html
Labels: documentation

#72 Add buttons for editing pages and reporting issues to docs
  .github/ISSUE_TEMPLATE/2-bug.yml
  _config-3.x.yml
  _config.yml
  _layouts/docs.html
  images/logos/doc-sections/bug.svg
  images/logos/doc-sections/edit.svg
Labels: enhancement, community

#71 Cleanup WireMock Cloud metadata and code usages
  .github/workflows/deploy.yaml
  _config.yml
  _includes/analytics-providers/google.html
  _includes/analytics.html
  _includes/masthead.html
  _sass/_homepage.scss
  _sass/_studio.scss
  assets/js/homeHeaderCard.js
  assets/js/tracking-events.js
  index.html
  studio/index.html
Labels: chore

#76 Add templates after the override
  .github/ISSUE_TEMPLATE/1-documentation.yml
  .github/ISSUE_TEMPLATE/2-enhancement.yml
  .github/ISSUE_TEMPLATE/3-bug.yml
  .github/ISSUE_TEMPLATE/4-chore.yml
  .github/ISSUE_TEMPLATE/config.yml
  _layouts/docs.html
Labels: chore

#73 Show anchor links when hovering over documentation headers
  _includes/anchor-headings.html
  _layouts/docs.html
  images/logos/doc-sections/link.svg
Labels: enhancement

#80 Restore UA analytics to the old property
  _config.yml
  _includes/analytics-providers/google.html
Labels: bug

#81 Update navlinks in the hamburger menu
  _includes/masthead.html
Labels: enhancement

#86 Fix the WireMock 3.x content inclusion
  .github/workflows/ci.yml
  .github/workflows/deploy.yaml
  .scripts/merge-sitemaps.rb
Labels: bug

#75 Add Breadcrumbs navigation to the documents
  _config.yml
  _docs/index.html
  _includes/breadcrumbs.html
  _includes/docs-sidebar.html
  _includes/nav-breadcrumb-icon.svg
  _includes/nav-breadcrumbs.html
  _layouts/docs.html
  _plugins/breadcrumbs.rb
  _plugins/drops/breadcrumb_item.rb
  _sass/_navigation.scss
  _sass/_page.scss
  _sass/_sidebar-docs.scss
  images/logos/doc-sections/home.svg
  images/logos/doc-sections/slack.svg
Labels: documentation

#85 Landing changes - low hanging fruit
  _docs/download-and-installation.md
  _includes/downloads.html
  _includes/footer.html
  _sass/_homepage.scss
  index.html
Labels: enhancement

#82 Navbar nesting links
  _data/navigation.yml
  _includes/masthead.html
  images/logos/doc-sections/cloud.svg
  images/logos/doc-sections/community.svg
  images/logos/doc-sections/document.svg
  images/logos/doc-sections/help-mono.svg
  images/logos/doc-sections/plus.svg
Labels: enhancement

#90 Improve Rendering for WireMock Cloud items
  _data/navigation.yml
  _includes/masthead.html
  _sass/_homepage.scss
  _sass/_masthead.scss
  _sass/_navigation.scss
  images/wiremock-cloud/wiremock_cloud_logo.png
  index.html
Labels: enhancement

#98 Add documentation root for WireMock Standalone
  _data/doc-categories.yml
  _docs/index.html
  _docs/standalone.md
  _docs/standalone/docker.md
Labels: enhancement

#100 Cleanup references to Mocklab examples in the documentation
  _docs/record-playback.md
  assets/js/wiremock-admin-api.json
  swagger/examples/record-spec.yaml
  swagger/wiremock-admin-api.yaml
Labels: chore

#99 Add support for links in the documentation navbar
  _data/doc-categories.yml
  _includes/docs-sidebar.html
  _sass/_sidebar-docs.scss
Labels: documentation, enhancement

#101 Update logos and remove old concepts
  images/favicon.svg
  images/favicon_big.png
  images/shortLogo.png
  images/wiremock-concept-01.png
  images/wiremock-concept-icon-01.png
  images/wiremock-concept-words-01.png
Labels: bug, chore

#102 Fix broken links
  _docs/java-usage.md
  _docs/junit-extensions.md
  _docs/junit-jupiter.md
  _docs/participate.md
  _docs/standalone.md
  _docs/standalone/admin-api-reference.md
  _docs/standalone/docker.md
  _includes/downloads.html
  support/index.md
Labels: bug

#103 Inject default og:image into the pages when no image set
  _includes/seo.html
Labels: bug

#104 More link fixes + documentation how to check them
  CONTRIBUTING.md
  _docs/advanced/deploy-to-servlet-container.md
  _docs/solutions/android.md
  _docs/solutions/jvm.md
  _docs/standalone/docker.md
  _docs/standalone/java-jar.md
Labels: bug, community

#110 Document the .NET solutions for WireMock
  _docs/solutions/dotnet.md
Labels: documentation

#111 Add documentation for WireMock API Templates Library
  _data/doc-categories.yml
  _data/navigation.yml
  _docs/index.html
  _docs/mock-api-templates.md
  _docs/mock-api-templates/usage.md
  images/logos/doc-sections/template.svg
Labels: documentation, enhancement

#70 Update the commercial support page
  _data/navigation.yml
  support/commercial.md
  support/index.md
Labels: enhancement
