Repository wiremock/wiremock.org, pull requests merged in 2023-08, with the labels that each got.

#130 Added Dockerfile and Docker compose examples
  _docs/response-templating.md
  _docs/standalone/docker.md
Labels: documentation

#135 Update Artifact locations for WireMock 3.x baseline
  _config-3.x.yml
  _docs/https.md
  _docs/proxying.md
  _docs/quickstart/java-junit.md
  _docs/request-matching.md
  _docs/standalone/java-jar.md
  _docs/webhooks-and-callbacks.md
  _includes/downloads.html
Labels: documentation

#139 Update links to Go WireMock on the solutions page
  _docs/solutions/golang.md
Labels: documentation

#144 Improve the Golang solution page
  _docs/solutions/golang.md
Labels: chore

#145 fix: bump latest `wiremock_beta_version` to `3.0.0-beta-15`
  _config-3.x.yml
  _config.yml
Labels: documentation

#143 Fix Testcontainers site URL in the solutions page
  _docs/solutions/testcontainers.md
Labels: bug

#43 Make WireMock 3.0 documentation the default one
  README.md
  _config_preview_public.yml
  _data/doc-categories.yml
  _docs/configuration.md
  _docs/extending-wiremock.md
  _docs/extensibility/adding-template-helpers.md
  _docs/extensibility/adding-template-model-data.md
  _docs/extensibility/custom-matching.md
  _docs/extensibility/extending-the-admin-api.md
  _docs/extensibility/filtering-requests.md
  _docs/extensibility/listening-for-serve-events.md
  _docs/extensibility/listening-for-settings-changes.md
  _docs/extensibility/listening-for-stub-changes.md
  _docs/extensibility/transforming-responses.md
  _docs/https.md
  _docs/proxying.md
  _docs/quickstart/java-junit.md
  _docs/request-matching.md
  _docs/response-templating.md
  _docs/standalone/java-jar.md
  _docs/webhooks-and-callbacks.md
  _includes/downloads.html
  assets/js/wiremock-admin-api.json
Labels: documentation

#156 Fix Maven bogus version in downloads
  _docs/download-and-installation.md
Labels: bug

#158 Add slash redirects to /docs/running-standalone
  _docs/standalone/java-jar.md
Labels: bug

#160 Fix redirects for Downloads
  _docs/download-and-installation.md
Labels: bug
